name: Main Workflow -- GRADLE

on:
  push:
    branches:
      - main
      - development
      - hotfix
    tags:
      - 'v*'
      - '*'
  workflow_dispatch:
    inputs:
      project-type:
        description: 'Specify the type of project (none, gradle, javascript, ruby, maven, more ...)'
        required: true
        default: 'gradle'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  call-sub-workflow:
    # Uses the main.yml workflow from techsur-ovh-deployments for deployment logic
    uses: techsur-solutions/techsur-ovh-deployments/.github/workflows/main.yml@main
    with:
      project-type: 'gradle'
      repository: ${{ github.repository }}
      branch-name: ${{ github.ref_name }}
      docker-context: '.'
      deployment-chart: 'rfpai-service'
    secrets: inherit