package solutions.techsur.rfpaiservice.entity;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonValue;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;
import lombok.experimental.SuperBuilder;

import org.hibernate.envers.AuditTable;
import org.hibernate.envers.Audited;

import solutions.techsur.common.microservice.entity.BaseEntity;

/**
 * Entity representing a compliance matrix item within a Request For Proposal (RFP).
 */
@Entity
@Table(name = "compliance_matrix")
@Audited
@AuditTable(value = "compliance_matrix_aud")
@SuperBuilder
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class ComplianceMatrix extends BaseEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    @Column(nullable = false)
    private String requirement;

    @Enumerated(EnumType.STRING)
    @Column(name = "compliance_status", nullable = false)
    private ComplianceStatus status = ComplianceStatus.PASS;

    private String justification;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "rfp_id", referencedColumnName = "id", nullable = false)
    @JsonBackReference
    private RequestForProposal proposal;

    @Column(name = "section_no")
    private String sectionNo;

    /**
     * Enumeration representing compliance status states.
     */
    public enum ComplianceStatus {
        FAIL("Fail"),
        PASS("Pass");

        private final String value;

        ComplianceStatus(String value) {
            this.value = value;
        }

        /**
         * Returns the string value of the compliance status for JSON serialization.
         * 
         * @return the string representation of the status.
         */
        @JsonValue
        public String getValue() {
            return value;
        }
    }

    // Getters and setters can be generated by Lombok's @SuperBuilder and annotations,
    // or customized methods can be added here if needed.
}