server:
  port: ${SERVER_PORT:8080}
  forward-headers-strategy: framework
  servlet:
    context-path: ${SERVER_SERVLET_CONTEXT_PATH:/rfpai}

spring:
  profiles:
    include: default
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB
  datasource:
    url: jdbc:postgresql://${APP_DB_HOST:localhost}:${APP_DB_PORT:5433}/${APP_DB_DATABASE:postgres}?currentSchema=${APP_DB_SCHEMA:rfpaiservice}
    username: ${APP_DB_USER:postgres}
    password: ${APP_DB_PASSWORD:5wmGWoQtv25tfUih}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximumPoolSize: ${SPRING_MAX_POOL_SIZE:20}
  jpa:
    show-sql: false
    properties:
      hibernate:
        default_schema: rfpaiservice
        show_sql: false
        format_sql: false
        order_inserts: true
        order_updates: true
        jdbc:
          lob.non_contextual_creation: true
          batch_size: 50
      org:
        hibernate:
          envers:
            store_data_at_delete: true
            store_data_at_update: true
    hibernate:
      ddl-auto: none
  task:
    scheduling:
      pool:
        size: 8
  liquibase:
    enabled: true
    contexts: dev
    change-log: classpath:db/changelog-master.xml
    liquibase-schema: liquibase
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${RFP_APP_JWT_ISSUER:http://localhost:8180/realms/coding-challenge}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
      client:
        provider:
          keycloak:
            token-uri: ${RFP_APP_JWT_ISSUER:http://localhost:8180/realms/coding-challenge}/protocol/openid-connect/token
        registration:
          keycloak:
            provider: keycloak
            authorization-grant-type: client_credentials
            client-id: ${RFP_SYSTEM_CLIENT_ID:system}
            client-secret: ${RFP_SYSTEM_CLIENT_SECRET:secret}
            scope: read,write
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  health:
    probes:
      enabled: true

springdoc:
  show-login-endpoint: true
  oAuthFlow:
    authorizationUrl: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/auth
    tokenUrl: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/token
  api-docs:
    enabled: ${SPRINGDOC_API_DOCS_ENABLED:true}
  swagger-ui:
    enabled: ${SPRINGDOC_SWAGGER_UI_ENABLED:true}
    supportedSubmitMethods: ${SPRINGDOC_SWAGGER_UI_SUPPORTED_SUBMIT_METHODS:get,put,post,delete,options,head,patch,trace}

logging:
  level:
    org.springframework.*: WARN
    org.apache.catalina.*: WARN
    com.zaxxer.hikari.*: WARN
    springfox.*: WARN
    org.hibernate.SQL: ERROR
    org.hibernate.type.descriptor.sql.BasicBinder: ERROR
common:
  microservice:
    cors:
      origins: ${COMMON_MICROSERVICE_CORS_ORIGINS:*}
      methods: ${COMMON_MICROSERVICE_CORS_METHODS:*}
      headers: ${COMMON_MICROSERVICE_CORS_HEADERS:*}
s3:
  region: us-east-1
  bucketName: ${RFP_S3_BUCKET:techsur-rfpaiservice}
  accessKey: ${TS_AWS_ACCESS_KEY:accessKey}
  secretKey: ${TS_AWS_SECRET_KEY:secretKey}
  baseFolder: ${RFP_S3_BASE_FOLDER:techsur/rfp}
  blueBookBaseFolder: ${RFP_S3_BASE_FOLDER:techsur/rfp}/bluebook

rfpaiapi:
  keycloak:
    url: ${KEYCLOAK_URL:http://localhost:8180}
    masterrealm: ${KEYCLOAK_MASTER_REALM:master}
    realm: ${RFP_KEYCLOAK_REALM:coding-challenge}
    user: ${KEYCLOAK_USER:admin}
    password: ${KEYCLOAK_PASSWORD:password}
  authority:
    upload-document: ${DOCUMENT_API_AUTHORITY_UPLOAD_DOCUMENT:contributor, admin}
    delete-proposal: ${RFP_API_AUTHORITY_DELETE:admin}


