sonar.projectKey=rfpai-service
sonar.projectName=RFPAI Service
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=build/classes/java/main
sonar.junit.reportPaths=build/test-results/test
sonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml