-- Drop old timestamp column if exists
ALTER TABLE rfpaiservice.compliance_matrix
  DROP COLUMN IF EXISTS created_at;

ALTER TABLE rfpaiservice.compliance_matrix_aud
  DROP COLUMN IF EXISTS created_at;

-- Add auditing columns with defaults and automatic updated timestamp
ALTER TABLE rfpaiservice.compliance_matrix
  ADD COLUMN IF NOT EXISTS created_by_name VARCHAR(100) NOT NULL DEFAULT 'System',
  ADD COLUMN IF NOT EXISTS updated_by_name VARCHAR(100) NOT NULL DEFAULT 'System',
  ADD COLUMN IF NOT EXISTS created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE rfpaiservice.compliance_matrix_aud
  ADD COLUMN IF NOT EXISTS created_by_name VARCHAR(100) NOT NULL DEFAULT 'System',
  ADD COLUMN IF NOT EXISTS updated_by_name VARCHAR(100) NOT NULL DEFAULT 'System',
  ADD COLUMN IF NOT EXISTS created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;