ALTER TABLE rfpaiservice.compliance_matrix
DROP COLUMN created_at;

ALTER TABLE rfpaiservice.compliance_matrix_aud
DROP COLUMN created_at;

ALTER TABLE rfpaiservice.compliance_matrix
ADD COLUMN created_by_name VARCHAR(100) NOT NULL DEFAULT 'System',
ADD COLUMN updated_by_name VARCHAR(100) NOT NULL DEFAULT 'System',
ADD COLUMN created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE rfpaiservice.compliance_matrix_aud
ADD COLUMN created_by_name VARCHAR(100) NOT NULL DEFAULT 'System',
ADD COLUMN updated_by_name VARCHAR(100) NOT NULL DEFAULT 'System',
ADD COLUMN created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;