ALTER TABLE rfpaiservice.rfps
DROP COLUMN IF EXISTS created_by;

ALTER TABLE rfpaiservice.rfps
DROP COLUMN IF EXISTS created_at;

ALTER TABLE rfpaiservice.rfp_documents
DROP COLUMN IF EXISTS uploaded_by;

ALTER TABLE rfpaiservice.rfp_documents
DROP COLUMN IF EXISTS uploaded_at;

ALTER TABLE rfpaiservice.rfp_documents_aud
DROP COLUMN IF EXISTS uploaded_by;

ALTER TABLE rfpaiservice.rfp_documents_aud
DROP COLUMN IF EXISTS uploaded_at;

ALTER TABLE rfpaiservice.rfps_aud
DROP COLUMN IF EXISTS created_by;

ALTER TABLE rfpaiservice.rfps_aud
DROP COLUMN IF EXISTS created_at;

ALTER TABLE rfpaiservice.rfps 
ADD COLUMN created_by_name VARCHAR(100) NOT NULL DEFAULT 'System',
ADD COLUMN updated_by_name VARCHAR(100) NOT NULL DEFAULT 'System',
ADD COLUMN created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE rfpaiservice.rfp_documents 
ADD COLUMN created_by_name VARCHAR(100) NOT NULL DEFAULT 'System',
ADD COLUMN updated_by_name VARCHAR(100) NOT NULL DEFAULT 'System',
ADD COLUMN created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE rfpaiservice.rfps_aud 
ADD COLUMN created_by_name VARCHAR(100) NOT NULL DEFAULT 'System',
ADD COLUMN updated_by_name VARCHAR(100) NOT NULL DEFAULT 'System',
ADD COLUMN created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE rfpaiservice.rfp_documents_aud
ADD COLUMN created_by_name VARCHAR(100) NOT NULL DEFAULT 'System',
ADD COLUMN updated_by_name VARCHAR(100) NOT NULL DEFAULT 'System',
ADD COLUMN created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;